from Classes.Graph import Graph

def generate_bidirect_graph():
    g = Graph()
    g.add_node("A")
    g.add_node("B")
    g.add_node("C")
    g.add_node("D")
    g.add_node("E")
    g.add_node("F")
    g.add_node("G")
    g.add_node("H")
    g.add_node("I")
    
    g.add_edge("A", "B")
    g.add_edge("A", "H")
    g.add_edge("B", "C")
    g.add_edge("B", "H")
    g.add_edge("C", "D")
    g.add_edge("C", "F")
    g.add_edge("C", "I")
    g.add_edge("D", "E")
    g.add_edge("D", "F")
    g.add_edge("E", "F")
    g.add_edge("F", "G")
    g.add_edge("G", "H")
    g.add_edge("G", "I")
    g.add_edge("H", "I")
    
def generate_bidirect_weighted_graph():
    g = Graph()
    g.add_node("A")
    g.add_node("B")
    g.add_node("C")
    g.add_node("D")
    g.add_node("E")
    g.add_node("F")
    g.add_node("G")
    g.add_node("H")
    g.add_node("I")
    
    g.add_edge("A", "B", 4)
    g.add_edge("A", "H", 8)
    g.add_edge("B", "C", 8)
    g.add_edge("B", "H", 11)
    g.add_edge("C", "D", 7)
    g.add_edge("C", "F", 4)
    g.add_edge("C", "I", 2)
    g.add_edge("D", "E", 9)
    g.add_edge("D", "F", 14)
    g.add_edge("E", "F", 10)
    g.add_edge("F", "G", 2)
    g.add_edge("G", "H", 1)
    g.add_edge("G", "I", 6)
    g.add_edge("H", "I", 7)

def generate_bidirect_coord_graph():
    g = Graph()
    g.add_node("A", (0,1))
    g.add_node("B", (1,0))
    g.add_node("C", (2,0))
    g.add_node("D", (3,0))
    g.add_node("E", (4,1))
    g.add_node("F", (3,2))
    g.add_node("G", (2,2))
    g.add_node("H", (1,2))
    g.add_node("I", (2,1))
    
    g.add_edge("A", "B")
    g.add_edge("A", "H")
    g.add_edge("B", "C")
    g.add_edge("B", "H")
    g.add_edge("C", "D")
    g.add_edge("C", "F")
    g.add_edge("C", "I")
    g.add_edge("D", "E")
    g.add_edge("D", "F")
    g.add_edge("E", "F")
    g.add_edge("F", "G")
    g.add_edge("G", "H")
    g.add_edge("G", "I")
    g.add_edge("H", "I")
    

def generate_bidirect_coord_weighted_graph():
    g = Graph()
    g.add_node("A", (0,1))
    g.add_node("B", (1,0))
    g.add_node("C", (2,0))
    g.add_node("D", (3,0))
    g.add_node("E", (4,1))
    g.add_node("F", (3,2))
    g.add_node("G", (2,2))
    g.add_node("H", (1,2))
    g.add_node("I", (2,1))
    
    g.add_edge("A", "B", 4)
    g.add_edge("A", "H", 8)
    g.add_edge("B", "C", 8)
    g.add_edge("B", "H", 11)
    g.add_edge("C", "D", 7)
    g.add_edge("C", "F", 4)
    g.add_edge("C", "I", 2)
    g.add_edge("D", "E", 9)
    g.add_edge("D", "F", 14)
    g.add_edge("E", "F", 10)
    g.add_edge("F", "G", 2)
    g.add_edge("G", "H", 1)
    g.add_edge("G", "I", 6)
    g.add_edge("H", "I", 7)